services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      OPENAI_API_KEY:  ${OPENAI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}  # Ensure the user and password match the DB settings
    depends_on:
      - db
    volumes:
      - ./:/app # Mount the application code into the container
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - mynetwork

volumes:
  postgres_data:
networks:
  mynetwork:
    driver: bridge